### ISSUE TITLE
Support MAF files

### ISSUE THREAD

**Issue by alirezaomidi** [google/nucleus#10]
Hi,
Are MAF files (Described [Here](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/)) supported by Nucleus?

**Comment by ThomasColthurst** [comment]
Not currently, but I'll add it to our list of file formats to consider.

One initial concern is that the TCGA Mutation Annotation Format specification link on that page is hidden behind an "iTrust" gateway.  We would need a fully public MAF spec in order to add them to Nucleus.
