### ISSUE TITLE
Example Binaries

### ISSUE THREAD

**Issue by kmanikumar** [google/nucleus#12]
Are the example binaries compiled if I install nucleus via pip? If so, where can I find them?

If not, do I have to run the install.sh script to build the example binaries?

**Comment by ThomasColthurst** [comment]
Yes, the example scripts are available if you pip install nucleus.  To find them, you will first need to find the directory where pip put nucleus.  If you run

$ python
>>> import sys
>>> print(sys.path)

it will be one of the listed directories, usually the one ending in "site-packages".  For example, it might be "/usr/local/lib/python2.7/site-packages/nucleus".  If so, then the example scripts will be in "/usr/local/lib/python2.7/site-packages/nucleus/examples", and you can run them by typing something like

$ python /usr/local/lib/python2.7/site-packages/nucleus/examples/filter_vcf input.vcf output.vcf

**Comment by kmanikumar** [comment]
@ThomasColthurst I noticed the scripts. Will running the example scripts as is achieve the same performance as binaries built using bazel build -c opt $COPT_FLAGS nucleus/examples:all ? If so, why build the examples at all.

**Comment by ThomasColthurst** [comment]
Yes, they will have the same performance.  You only need to build the examples if (a) you are not using the pip package or (b) you want to change the C++ code.
