### ISSUE TITLE
cannot import name 'tfrecord_reader' (python3)

### ISSUE THREAD

**Issue by TimSmole** [google/nucleus#14]
### Problem:
When I try to import the vcf module I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nucleus-0.3.0/nucleus/io/vcf.py", line 64, in <module>
    from nucleus.io import genomics_reader
  File "/usr/local/lib/python3.5/dist-packages/nucleus-0.3.0/nucleus/io/genomics_reader.py", line 68, in <module>
    from nucleus.io.python import tfrecord_reader
ImportError: cannot import name 'tfrecord_reader'
```

I installed google-nucleus library from source, since it is not available through pip3 as described in issue #9 .

### Steps to reproduce:

Dockerfile:
```
FROM tensorflow/tensorflow:1.13.1-gpu-py3-jupyter

RUN apt-get update && apt-get install -y --no-install-recommends sudo

# Install nucleus from source since it is not available through pip3
RUN cd /usr/local/lib/python3.5/dist-packages/ && \
    curl -SL https://github.com/google/nucleus/archive/0.3.0.tar.gz | tar xz && \
    cd nucleus-0.3.0 && source install.sh

ENV PYTHONPATH="$PYTHONPATH:/usr/local/lib/python3.5/dist-packages/nucleus-0.3.0/"

# Try to import vcf to reproduce an error
CMD ["python", "-c", "from nucleus.io import vcf"]
```

within the directory containing the Dockerfile run:
```
docker build -t test .
docker run test
```

Any help would by highly appreciated!

**Comment by ThomasColthurst** [comment]
Hi!  What you are trying to do here doesn't work -- there is no "install nucleus from source" recipe.  Instead, if you wish to build Nucleus from its source and use that with your own code, you will need to also build your own code using Bazel.

Note that as is, the end result of that will also not work with Python 3.  The reason is that Nucleus depends on multiple C++ extension modules, and the C++ extension module interface changed between Python 2 and Python 3.

We are actively working on getting a Python 3 compliant pip package for Nucleus, and we hope to be able to announce it soon.

**Comment by ThomasColthurst** [comment]
Nucleus 0.4 now has a Python 3 compatible pip package.

**Comment by alonsozarate** [comment]
Hi,
I am having problems to use nucleus.
At first, if I try to import packages I have import errors and I am looking some source but I did not find anything about this

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-16-4642d8e42f94> in <module>
----> 1 from nucleus.io import fasta

c:\users\local\python36\lib\site-packages\nucleus\io\fasta.py in <module>
     42 import six
     43 
---> 44 from nucleus.io import gfile
     45 from nucleus.io import genomics_reader
     46 from nucleus.io.python import reference

c:\users\local\python36\lib\site-packages\nucleus\io\gfile.py in <module>
     20 import six
     21 
---> 22 from nucleus.io.python import gfile
     23 
     24 

ImportError: cannot import name 'gfile'

Please if you can help me with this
