### ISSUE TITLE
python2 import error

### ISSUE THREAD

**Issue by paradisebee** [google/nucleus#19]
Have tried to install with pip and pip2.

Import nucleus in **Python3** works fine. 
Import nucleus in **Python2** fails with the following error:

Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nucleus
>>> from nucleus.io import vcf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/nucleus/io/vcf.py", line 64, in <module>
    from nucleus.io import genomics_reader
  File "/home/user/.local/lib/python2.7/site-packages/nucleus/io/genomics_reader.py", line 68, in <module>
    from nucleus.io.python import tfrecord_reader
ImportError: /home/user/.local/lib/python2.7/site-packages/nucleus/io/python/tfrecord_reader.so: undefined symbol: _Py_FalseStruct
>>>

I found an answer to this error:
 https://github.com/tensorflow/tensorflow/issues/16720#issuecomment-363509113

but I am not sure what I did wrong.
I have removed and recreated the environment many times.

**Comment by ThomasColthurst** [comment]
Nucleus 0.4.1 only works with Python 3.  To use Nucleus with Python 2, you will need to run
$ pip install --user google-nucleus==0.3.2

**Comment by paradisebee** [comment]
Thank you. A small suggestion, I don't see any documents saying 0.4.1 drops support for python2. Can you make it more explicit?

**Comment by ThomasColthurst** [comment]
Good idea!  I've updated the install instructions in the README as you suggest.
