### ISSUE TITLE
Apache Beam integration

### ISSUE THREAD

**Issue by TimSmole** [google/nucleus#20]
Hi,

I have a question regarding Nucleus and Apache Beam integration. I've recently [read](https://issues.apache.org/jira/browse/BEAM-5628) that Nucleus will not replace [PyVCF](https://github.com/jamescasbon/PyVCF) that is currently used by Apache Beam and so 

> Beam might have to drop support for VCF IO once Beam drops support of Python 2

I am curious if there are any plans for Nucleus-Beam integration or perhaps any suggestions on how to read VCF files with Nucleus and serve them to Beam Pipeline? Should one first read the VCFs with Nucleus write it as TFRecord and then use Beam's [tfrecordio module](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/tfrecordio.py) to read those? This seems a bit clumsy and counter-intuitive. Any advice on how to approach this more elegantly will be highly appreciated.

Thanks!

**Comment by ThomasColthurst** [comment]
It's a good question.  We (on the Nucleus team) don't have any immediate plans for better Nucleus-Beam integration than what exists at present.  Some of the current approaches are:

1) For reading one small to medium size VCF file, just read all of the variants into memory:

reader = vcf.VcfReader(filename)
input_vcf_records = pipeline | beam.Create(list(reader.iterate()))

2) For reading many small to medium sized VCF files, create a PCollection with the filenames, and then map them to their records:

filenames = glob.glob("*.vcf.gz")
filename_pcollection = pipeline | beam.Create(filenames)
variants = filename_pcollection | 'ReadVcfs' >> beam.Map(lambda f: list(vcf.VcfReader(f)))

3) For reading one or more large VCFs, do the same as #2, but start from a PCollection of (filename, range) tuples and then do query operations on the VcfReader objects inside the beam.Map :

chunks = pipeline | bream.Create(list(range(10)))
variants = chunks | 'QueryVcfs' >> beam.Map(
  lambda i: list(vcf.VcfReader("big.vcf.gz").query(
    ranges.parse_literal('chr3:%d-%d' % (i * 1e5, (i+1) * 1e5)))))

**Comment by TimSmole** [comment]
@ThomasColthurst Thanks for saving the day once again!
