### ISSUE TITLE
User Menu for Nucleus

### ISSUE THREAD

**Issue by KuangXY3** [google/nucleus#27]
Hello,

Do you have user menu for nucleus, which explain each class, function and argument?
For example, what are nucleus.protos and reads_pb2.

Thank you!

**Comment by pichuan** [comment]
Hi @KuangXY3 ,
Currently the best explanations are in the comments in the files themselve. For example, for `reads_pb2`, please refer to the original definition here:
https://github.com/google/nucleus/blob/master/nucleus/protos/reads.proto

To read more about Protocol Buffers, please read: https://developers.google.com/protocol-buffers

**Comment by ThomasColthurst** [comment]
For the Python code, there is also documentation for all of the functions at
https://github.com/google/nucleus/blob/master/docs/source/doc_index.md
