### ISSUE TITLE
hdf5 file format not supported

### ISSUE THREAD

**Issue by tkolarik** [google/nucleus#28]
This is a common format for sequencing data storage in my field, I hope you will consider supporting it!

**Comment by pichuan** [comment]
Hi @tkolarik 
Thank you for your feedback! We will take this into account in the future but cannot guarantee a timeline.

Can you maybe give a few specific examples on how you're using Nucleus now, and specific examples on how having this format will help in your workflow?

**Comment by tkolarik** [comment]
I guess what I am asking is specifically to support TASSEL's specific implementation of the format.
Tassel is a great tool for working with Maize genome datasets
https://www.maizegenetics.net/tassel 
and the HDF5 format is fast.

> HDF5 format is designed to allow rapid access to large datasets. The full specification can be found at the HDF Group ( http://www.hdfgroup.org/HDF5 ), but unless you are actively developing new code for TASSEL, you probably don't need to worry about it. In brief, HDF5 is basically a self-contained file system that lets you rapidly access large datasets without having to load them into memory. Since there is no standard HDF5 specification for genomic data, TASSEL's HDF5 files can only really be used by TASSEL; if you want another program to access the same data, you will need to export it to a different format.

Looking at some files myself, the format used does not seem overly complex.

Thank you for your consideration.

**Comment by pichuan** [comment]
Thank you for the information! We'll take this into consideration in the future.

Note that Nucleus takes user's pull requests. So if the feature seems easier to implement here, please feel free to send us pull requests to review if you like.
