### ISSUE TITLE
Is there any limitation for calling rare mutation?

### ISSUE THREAD

**Issue by WeiweiBian** [google/nucleus#29]
Hi,
Thanks for the magic library you developed.
I wonder whether this can be used for rare mutation calling with MAF around or below 1%. I remember that there is a limitation from Deepvariant that the maximum read depth is 362 due to the Inception v3. I wonder whether this limitation also works with Nucleus.
Thanks!
Best,
Weiwei

**Comment by akolesnikov** [comment]
Hi Weiwei,

There shouldn't be a restriction for read depth in Nucleus. If you could explain in more details what exactly you are trying to do with Nucleus I would be able to be more specific.

Best,
Alex

**Comment by WeiweiBian** [comment]
Hi Alex,
Thanks a lot for your reply.
We planned to adapt the Nucleus to a somatic mutation caller with error correction, the sequencing depth is quite high but the MAF for the mutation is ultra-low, around 1%. I wonder whether the Nucleus works in this scenario.
Thanks!
Best,
Weiwei
