### ISSUE TITLE
FASTQ parser does not validate + line

### ISSUE THREAD

**Issue by peterjc** [google/nucleus#3]
You define a constant ``SEQUENCE_AND_QUALITY_SEPARATOR_SYMBOL`` but never confirm that the third line of each FASTQ record starts with this (nor any further sanity tests of this line):

https://github.com/google/nucleus/blob/163820ee1f27d3b50f596ac532de1ac2c723ddf4/nucleus/io/fastq_reader.cc#L44

**Comment by cmclean** [comment]
Thanks. Fixed in https://github.com/google/nucleus/commit/073c3c7af4ed0e3f401f8780417e9858f53b401f .
