### ISSUE TITLE
RuntimeError: PythonNext() argument variant is not valid: Dynamic cast failed.

### ISSUE THREAD

**Issue by Biogitte** [google/nucleus#32]
Hi,

As I am using Mac-OS, I have set up a Docker environment to run Nucleus with Tensorflow in a Jupyter Notebook. 

For the Docker image/container I am using the base-image "python:3.6-buster" as Nucleus doesn't work with Python 3.8. Here is the Dockerfile that I use:

```
# download base image
FROM python:3.6-buster

# dealing with cache issues
RUN apt-get clean
RUN apt-get update

# keep pip below v.21
RUN pip3 install --upgrade pip==20.2.3

# copy and paste the src directory into the image
WORKDIR src/
COPY . .

RUN pip3 install -r requirements.txt

```

For the dependencies (requirements.txt) I have tried with the latest versions of Tensorflow and Nucleus, as well as 
Nucleus v. 0.4.1 and Tensorflow v.1.13.1 as suggested [here](https://github.com/google/nucleus/issues/15). 

Inside the Jupyter Notebook (that is running in the Docker container), I am re-installing protobuf (i.e., `!pip3 install --force-reinstall --upgrade protobuf`).

But when trying to test-run this code:

```
from nucleus.io import vcf
r = vcf.VcfReader('<sample>.vcf')
for v in r:
  print(v.start)
```

I am getting this error: `RuntimeError: PythonNext() argument variant is not valid: Dynamic cast failed`.

I have tried different hacks and tricks to get around the error (changing pip versions, different python versions (3.6, and 3.7, different Tensorflow and Nucleus, etc.) in the Docker container. Unfortunately, I forgot to log everything I have tried to get past this issue the last couple of days. 

Is there a way to get around this issue? 

Thanks,

Best wishes, Birgitte

**Comment by ThomasColthurst** [comment]
Hi, Birgitte.  I'm afraid that Nucleus doesn't work on Mac OS; we only support Linux for now.  Sorry!
