### ISSUE TITLE
Nucleus Proto is colliding with Tensorflow protos?

### ISSUE THREAD

**Issue by moonjo-geno** [google/nucleus#34]
Hello,

I'm trying to use the nucleus.io's tfrecord functions.
When I'm importing as shown below, I get a TypeError. It looks like protos are colliding and I'm not sure how to fix this as I want to use Example and Feature protos provided in nucleus.

I have two directories, dir1 and dir2. In dir1, I import tensorflow and it has test files. In dir2, I import nucleus.io. When I run pytest on dir1 and dir2, separately, they both work. However, when I change to the parent directory and run pytest, I get this error. Please help.

Thank you in advance,
Moonjo

    from nucleus.io import tfrecord
/root/.local/lib/python3.7/site-packages/nucleus/io/tfrecord.py:35: in <module>
    from nucleus.protos import example_pb2
/root/.local/lib/python3.7/site-packages/nucleus/protos/example_pb2.py:16: in <module>
    from nucleus.protos import feature_pb2 as nucleus_dot_protos_dot_feature__pb2
/root/.local/lib/python3.7/site-packages/nucleus/protos/feature_pb2.py:23: in <module>
    serialized_pb=_b('\n\x1cnucleus/protos/feature.proto\x12\ntensorflow\"\x1a\n\tBytesList\x12\r\n\x05value\x18\x01 \x03(\x0c\"\x1e\n\tFloatList\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x1e\n\tInt64List\x12\x11\n\x05value\x18\x01 \x03(\x03\x42\x02\x10\x01\"\x98\x01\n\x07\x46\x65\x61ture\x12+\n\nbytes_list\x18\x01 \x01(\x0b\x32\x15.tensorflow.BytesListH\x00\x12+\n\nfloat_list\x18\x02 \x01(\x0b\x32\x15.tensorflow.FloatListH\x00\x12+\n\nint64_list\x18\x03 \x01(\x0b\x32\x15.tensorflow.Int64ListH\x00\x42\x06\n\x04kind\"\x83\x01\n\x08\x46\x65\x61tures\x12\x32\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32!.tensorflow.Features.FeatureEntry\x1a\x43\n\x0c\x46\x65\x61tureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.tensorflow.Feature:\x02\x38\x01\"3\n\x0b\x46\x65\x61tureList\x12$\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x13.tensorflow.Feature\"\x9c\x01\n\x0c\x46\x65\x61tureLists\x12?\n\x0c\x66\x65\x61ture_list\x18\x01 \x03(\x0b\x32).tensorflow.FeatureLists.FeatureListEntry\x1aK\n\x10\x46\x65\x61tureListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.tensorflow.FeatureList:\x02\x38\x01\x42,\n\x16org.tensorflow.exampleB\rFeatureProtosP\x01\xf8\x01\x01\x62\x06proto3')
/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py:965: in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
E   TypeError: Couldn't build proto file into descriptor pool!
E   Invalid proto descriptor for file "nucleus/protos/feature.proto":
E     tensorflow.BytesList.value: "tensorflow.BytesList.value" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.BytesList: "tensorflow.BytesList" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FloatList.value: "tensorflow.FloatList.value" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FloatList: "tensorflow.FloatList" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Int64List.value: "tensorflow.Int64List.value" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Int64List: "tensorflow.Int64List" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Feature.kind: "tensorflow.Feature.kind" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Feature.bytes_list: "tensorflow.Feature.bytes_list" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Feature.float_list: "tensorflow.Feature.float_list" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Feature.int64_list: "tensorflow.Feature.int64_list" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Feature: "tensorflow.Feature" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Features.feature: "tensorflow.Features.feature" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Features.FeatureEntry.key: "tensorflow.Features.FeatureEntry.key" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Features.FeatureEntry.value: "tensorflow.Features.FeatureEntry.value" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Features.FeatureEntry: "tensorflow.Features.FeatureEntry" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Features: "tensorflow.Features" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureList.feature: "tensorflow.FeatureList.feature" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureList: "tensorflow.FeatureList" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureLists.feature_list: "tensorflow.FeatureLists.feature_list" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureLists.FeatureListEntry.key: "tensorflow.FeatureLists.FeatureListEntry.key" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureLists.FeatureListEntry.value: "tensorflow.FeatureLists.FeatureListEntry.value" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureLists.FeatureListEntry: "tensorflow.FeatureLists.FeatureListEntry" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.FeatureLists: "tensorflow.FeatureLists" is already defined in file "tensorflow/core/example/feature.proto".
E     tensorflow.Feature.bytes_list: "tensorflow.BytesList" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.Feature.float_list: "tensorflow.FloatList" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.Feature.int64_list: "tensorflow.Int64List" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.Features.FeatureEntry.value: "tensorflow.Feature" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.Features.feature: "tensorflow.Features.FeatureEntry" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.FeatureList.feature: "tensorflow.Feature" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.FeatureLists.FeatureListEntry.value: "tensorflow.FeatureList" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.
E     tensorflow.FeatureLists.feature_list: "tensorflow.FeatureLists.FeatureListEntry" seems to be defined in "tensorflow/core/example/feature.proto", which is not imported by "nucleus/protos/feature.proto".  To use it here, please add the necessary import.

**Comment by gunjanbaid** [comment]
@moonjo-geno what versions of TensorFlow and Nucleus are you using?

**Comment by moonjo-geno** [comment]
I'm using tensorflow 2.4.0 and 0.5.7 for google-nucleus

**Comment by gunjanbaid** [comment]
@moonjo-geno those versions should be compatible, so I am not yet sure what is causing the issue. Could you share some more details on the operating system and protobuf version you are using? If you have a toy example that I could use to reproduce the issue, that would be helpful as well.

**Comment by gunjanbaid** [comment]
A few more followup questions:
* Are either dir1 or dir2 called `nucleus` or `tensorflow`? That may cause problems.
* What happens when you run pytest from the parent directory of the parent directory of dir1 and dir2?

**Comment by moonjo-geno** [comment]
@gunjanbaid  I'm running it on ubuntu and the protobuf is 3.15.1 

I found a workaround since I last commented on this thread. My directory structure is:

root
        - dir1
                 - models
                           - __init__.py 
                           - mymodel.py (import tensorflow)
                           - mymodel_test.py. (import dir1.models.mymodel)
        - dir2
                - subdir
                            - __init__.py
                            - mytool.py (from nucleus.io import tfrecord)
                            - mytool_test.py (import dir2.subdir.mytool)

Neither of dir1 or dir2 is called nucleus or tensorflow. When I took a look at nucleus.proto and tensorflow.core.example, I noticed that the proto files had the same package name, which is probably why the collision is happening. What is strange is that when I created a 'tests' directory under 'dir1' and moved mymodel_test.py, (also created __init__.py in that directory), the error stopped happening. I'd like to keep the directory structure like this, however. I wonder what the best solution would be?

**Comment by gunjanbaid** [comment]
@moonjo-geno perhaps the error goes away with the `tests` dir because the order in which the `import tensorflow` and `from nucleus.io import tfrecord` lines are run changes. Does adding `from nucleus.io import tfrecord` to `mymodel.py` before the `import tensorflow` line fix the issue? If so, this could be a temporary fix.

**Comment by moonjo-geno** [comment]
I've added `from nucleus.io import tfrecord` before  the import tensorflow line and it fixed the issue. However, nucleus.io.tfrecord is not used in mymodel.py yet and so the nucleus import is unused and causes a warning. Is this because the proto is being shadowed? Thank you.

**Comment by cmclean** [comment]
Yes, that is correct. To quiet the warning if `tfrecord` is unused you can just do the following...

```
from nucleus.io import tfrecord
del tfrecord
```
