### ISSUE TITLE
Failed to install google-nucleus

### ISSUE THREAD

**Issue by CodyMarkix** [google/nucleus#35]
So I've been trying to install google-nucleus for something and it doesn't install for some reason.

It just apparently errors out with an exit status of one.

What can I do to fix this?
[Here's the installation log](https://github.com/google/nucleus/files/6869326/nucleus_log.txt)

**Comment by gunjanbaid** [comment]
@Hplr63 what OS are you using? Nucleus currently only works on modern Linux systems. We also do not yet support Python 3.9 or Python 3.8. For the latest version of Nucleus, v0.5.8, we recommend Python 3.6 or 3.7.

**Comment by cmclean** [comment]
Closing this stagnant issue. @CodyMarkix feel free to re-open if you provide additional information that can aid debugging.
