### ISSUE TITLE
Nucleus Proto is colliding with Tensorflow protos

### ISSUE THREAD

**Issue by flowers9** [google/nucleus#36]
Sorry for the repeat, but I'm having the same issue and the suggested workaround is not working for me.

My setup is on ubuntu 20.04, 64-bit.

I have a miniconda (python 3.8) that I installed both tensorflow 2.6.0 and google-nucleus 0.6.0 into (and a bunch of other stuff - I'm trying to run deepconsensus).  My test case script is trivial:

>import tensorflow as tf
from nucleus.io import tfrecord

with errors being of the form

>File "/home/flowers/test/miniconda3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 983, in __new__
>    return _message.default_pool.AddSerializedFile(serialized_pb)
>TypeError: Couldn't build proto file into descriptor pool!
>Invalid proto descriptor for file "nucleus/protos/feature.proto":
  tensorflow.BytesList.value: "tensorflow.BytesList.value" is already defined in file "tensorflow/core/example/feature.proto".

If I reverse the order of the two statements, I get the same error with the names switched:

>File "/home/flowers/test/miniconda3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 983, in __new__
>return _message.default_pool.AddSerializedFile(serialized_pb)
>TypeError: Couldn't build proto file into descriptor pool!
>Invalid proto descriptor for file "tensorflow/core/example/feature.proto":
  tensorflow.BytesList.value: "tensorflow.BytesList.value" is already defined in file "nucleus/protos/feature.proto".

Any suggestions as to how to get this to work?

**Comment by flowers9** [comment]
Well, I downloaded nucleus, changed the nucleus/protos/feature.proto and example.proto to have "nucleus" instead of "tensorflow" for the java_package and package names, ran protoc over them to create the *.py files, dropped those into my miniconda library to replace the existing ones, and it worked.

Looks like it was a simple namespace conflict?

Still can't get the deepconsensus tests to work, but hopefully it's not a nucleus issue, anymore. ;)

**Comment by MariaNattestad** [comment]
DeepConsensus requires Python >=3.6, <3.7, see the page on PyPI: https://pypi.org/project/deepconsensus/ and if that doesn't work for you, then please file an issue in https://github.com/google/deepconsensus/issues.

**Comment by akolesnikov** [comment]
Also, Nucleus doesn't support Python 3.8 yet (https://github.com/google/nucleus#installation)

**Comment by flowers9** [comment]
While I ran across the issue while attemping to get deepconsensus to work, it's a nucleus issue, which is why I opened an issue here.

And, as of three days ago, it looks like nucleus does support python 3.8, according to the tag notes.

And, honestly, it's all moot to me, I just thought you all might have been interested.

**Comment by MariaNattestad** [comment]
Sorry for the confusion.

The latest Nucleus version 0.6.0 does support python 3.8, but DeepConsensus comes with Nucleus 0.5.8. See requirements in DeepConsensus: https://github.com/google/deepconsensus/blob/main/requirements.txt.
We are working on making this smoother in future versions of DeepConsensus, so please stay tuned!

I meant that if you later can't get the DeepConsensus tests passing, then you can file another issue under DeepConsensus so others can find it if they have similar issues.

**Comment by flowers9** [comment]
Nah, part of why this is moot is that I later set up a miniconda environment with python 3.6 and (after a bit of work) was able to install deepconsensus with pip and get it to pass the tests.  Currently running the setup bits on a dataset I have (the pacbio part of the run ;).

**Comment by MariaNattestad** [comment]
Glad to hear you got it working!
