### ISSUE TITLE
Error runing codelab : dna_sequencing_error_correction

### ISSUE THREAD

**Issue by CDC1688** [google/nucleus#38]
Hi , 

I was simply just run all Codelab tutorial and got this error with nucleus. I think the tutorial is built with nucleus 0.5.6 & tf 2.3 . Is there any specific requirement for python verson? There seems to be a post about using protobuf verison 3.9.2 , should I try to install this. 

![image](https://user-images.githubusercontent.com/46419711/145329851-7ffd523e-1e29-486c-a2af-a443d49a8c6b.png)

**Comment by ThomasColthurst** [comment]
Hi!  Thanks for this error report!  It looks like the NIH has changed some of their file names so the VCF file the codelab used to download from ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/latest/GRCh37/HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz
no longer exists.  We'll reach out to them and try to fix this very soon.

Thanks again!

**Comment by ThomasColthurst** [comment]
All fixed now!  Please let us know if you have any further issues!

**Comment by CDC1688** [comment]
The Codelab is working now, thanks for your quick response
