### ISSUE TITLE
Read strand

### ISSUE THREAD

**Issue by sssxie** [google/nucleus#39]
I would like to know how to get the strand information of the read from nucleus.io.sam.SamReader, since I am working with bam files of long-read transcriptome.

**Comment by pichuan** [comment]
Hi @sssxie 
Use this field: https://github.com/google/nucleus/blob/68d3947fafba1337f294c0668a6e1c7f3f1273e3/nucleus/protos/position.proto#L32

For example, in DeepVariant we use the strand information as one of our channels in our representation. Here is the C++ code that reads it: https://github.com/google/deepvariant/blob/c8fae5bd5f6c587bba733d83263a694aca252098/deepvariant/pileup_image_native.cc#L296

You can access the same field in the Python code as well once you have a Read.
