### ISSUE TITLE
Use FASTQ test suite from Cock et al?

### ISSUE THREAD

**Issue by peterjc** [google/nucleus#4]
This is a little self promotion, but I'd encourage you to use the problematic FASTQ files (tar-ball) provided as supplementary material in our paper about the file format for your test suite:

The Sanger FASTQ file format for sequences with quality scores, and the Solexa/Illumina FASTQ variants. P.J.A. Cock, C.J. Fields, N. Goto, M.L. Heuer and P.M. Rice. *Nucleic Acids Research*, 2010, 38(6), 1767-1771. http://dx.doi.org/10.1093/nar/gkp1137

Note that Illumina moved over to the standard Sanger quality encoding as of v1.8 of their pipeline, see also https://en.wikipedia.org/wiki/FASTQ_format

**Comment by ThomasColthurst** [comment]
Great idea!  What license are the test files provided under?

**Comment by peterjc** [comment]
NAR did something silly with the tar-ball file's extension, took me a few goes to get it to unzip. Quoting the start of our ``README.txt`` from the archive:

```
This README file describes the FASTQ example files provided as supplementary
information to the open-access publication:

P.J.A. Cock, C.J. Fields, N. Goto, M.L. Heuer and P.M. Rice (2009). The Sanger
FASTQ file format for sequences with quality scores, and the Solexa/Illumina
FASTQ variants.

These files are provided freely and we encourage anyone writing a FASTQ parser
to use them as part of your test suite. Permission is granted to freely
distribute and modify the files. We request (but do not insist) that this
README file is included, or at least a reference to the above paper. Please
cite the above paper if appropriate. We also request (but do not insist) that
the example files are not modified, in order that they may serve as a common
reference.
```

You can also see the files as used in Biopython at https://github.com/biopython/biopython/tree/master/Tests/Quality along with other examples you might find helpful.

**Comment by peterjc** [comment]
P.S. The paper ended up with a 2010 publication date, nowadays I'd have done a preprint and had the preprint's DOI in the README but nevermind - the README is stuck with a 2009 date on the expected reference.

**Comment by pichuan** [comment]
Hi @peterjc ,
I'm looking through open issues and making sure I understand them.

If I understand correctly, the request here is to consider adding test data, and specifically the ones we can see here: https://github.com/biopython/biopython/tree/master/Tests/Quality

And I think @ThomasColthurst 's question was around the license. If I understand correctly,  it's hard for us to take in data or library that doesn't have a standard license that we can take. Nucleus itself is under Apache License 2.0.

I think there isn't clear actions we can take right now. I'd be interested to poke around and see if any of our tests actually failed on those files, but we likely won't take them in as part of Nucleus release. Thank you!

**Comment by peterjc** [comment]
The request was to use the (small) set of files with the NAR paper, terms:

```
These files are provided freely and we encourage anyone writing a FASTQ parser
to use them as part of your test suite. Permission is granted to freely
distribute and modify the files. We request (but do not insist) that this
README file is included, or at least a reference to the above paper. Please
cite the above paper if appropriate. We also request (but do not insist) that
the example files are not modified, in order that they may serve as a common
reference.
```

Yes, in hindsight a more explicit standard license would have been better - but is that not OK as is? We (the NAR paper co-authors) could in theory formally dual/re license this for your needs - what would be acceptable?

Or, there is the larger set of examples (including the NAR ones and more) with Biopython, which is under a liberal but unique license (and we are in the process of moving to dual licensing with the 3-clause BSD license).
