### ISSUE TITLE
Nucleus not building for Python3.7-3.9 via pip.

### ISSUE THREAD

**Issue by apilaskowski** [google/nucleus#41]
I am trying to build a Docker image, which will have a nucleus installed.

Currently I have such a file:

```
FROM ubuntu:latest

WORKDIR /test/

RUN apt -y update && apt install -y \
    software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa

RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata

RUN apt -y update && apt install -y \
    python3.7 \
    python3.7-distutils \
    curl

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.7 get-pip.py

RUN python3.7 -m pip install google-nucleus

COPY example.vcf /test/

CMD /bin/bash
```

I managed to install nucleus for Python3 version 10+, however, there is a problem with Python removing some collections, which your are using.

Currently, for this installation (I tried also python 3.9) I am receiving following log:

```
Building wheels for collected packages: google-nucleus, intervaltree, crcmod, dill, docopt
  Building wheel for google-nucleus (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      This package does not support wheel creation.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for google-nucleus
  Running setup.py clean for google-nucleus
  Building wheel for intervaltree (setup.py) ... done
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26100 sha256=1b59ccfb155513ee60dad398c484e6495a1675d9db312c7c8b5c02ec1b660997
  Stored in directory: /root/.cache/pip/wheels/ab/fa/1b/75d9a713279796785711bd0bad8334aaace560c0bd28830c8c
  Building wheel for crcmod (setup.py) ... done
FROM ubuntu:latest
  Created wheel for crcmod: filename=crcmod-1.7-py3-none-any.whl size=18834 sha256=9b30119c33f15d631de7cf9e9951031770c5bb098860bc633a8a33732de511a0
  Stored in directory: /root/.cache/pip/wheels/4a/6c/a6/ffdd136310039bf226f2707a9a8e6857be7d70a3fc061f6b36
  Building wheel for dill (setup.py) ... done
  Created wheel for dill: filename=dill-0.3.1.1-py3-none-any.whl size=78544 sha256=2e36ffde415b6526c1e157d895b7bfa00ef526f1b10f2076ffdbf72c80e7fbf3
  Stored in directory: /root/.cache/pip/wheels/4f/0b/ce/75d96dd714b15e51cb66db631183ea3844e0c4a6d19741a149
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=a81345c43fee7ab5e75b827c4e34d6112f00de5b30be2b93465edfe968e85c91
  Stored in directory: /root/.cache/pip/wheels/70/4a/46/1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
Successfully built intervaltree crcmod dill docopt
Failed to build google-nucleus
Installing collected packages: wcwidth, sortedcontainers, pytz, pure-eval, ptyprocess, pickleshare, executing, docopt, crcmod, backcall, urllib3, typing-extensions, traitlets, python-dateutil, pymongo, pygments, pydot, protobuf, prompt-toolkit, Pillow, pexpect, parso, orjson, numpy, mock, intervaltree, idna, grpcio, fastavro, dill, decorator, contextlib2, cloudpickle, charset-normalizer, certifi, asttokens, absl-py, stack-data, requests, pyarrow, proto-plus, matplotlib-inline, jedi, ipython, hdfs, apache-beam, google-nucleus
  Running setup.py install for google-nucleus ... done
  DEPRECATION: google-nucleus was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
Successfully installed Pillow-9.1.1 absl-py-1.1.0 apache-beam-2.40.0 asttokens-2.0.5 backcall-0.2.0 certifi-2022.6.15 charset-normalizer-2.1.0 cloudpickle-2.1.0 contextlib2-21.6.0 crcmod-1.7 decorator-5.1.1 dill-0.3.1.1 docopt-0.6.2 executing-0.8.3 fastavro-1.5.2 google-nucleus grpcio-1.47.0 hdfs-2.7.0 idna-3.3 intervaltree-3.1.0 ipython-8.4.0 jedi-0.18.1 matplotlib-inline-0.1.3 mock-4.0.3 numpy-1.22.4 orjson-3.7.5 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.30 proto-plus-1.20.6 protobuf-3.20.1 ptyprocess-0.7.0 pure-eval-0.2.2 pyarrow-7.0.0 pydot-1.4.2 pygments-2.12.0 pymongo-3.12.3 python-dateutil-2.8.2 pytz-2022.1 requests-2.28.1 sortedcontainers-2.4.0 stack-data-0.3.0 traitlets-5.3.0 typing-extensions-4.2.0 urllib3-1.26.9 wcwidth-0.2.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

This is happening during the google-nucleus installation process.
Could someone help me with that? 
I am out of ideas of what to do from here.

This is the communicate that I am receiving for default Python (version 3.10.4).
<img width="726" alt="Screenshot 2022-07-01 at 10 54 04" src="https://user-images.githubusercontent.com/19377908/176861241-d4f12acb-2675-492c-bb24-074ea30bc1a4.png">
.

**Comment by kishwarshafin** [comment]
@apilaskowski,

1) Regarding the python3.7 installation. Please see this section of our installation documentation: https://github.com/google/nucleus#installation
```
You can ignore any "Failed building wheel for google-nucleus" error messages -- these are expected and won't prevent Nucleus from installing successfully.
```
So I think your installation went fine. Please try to use the package in python environment to confirm.


2) For python3.10, it looks like python has removed `MutableSequence` from `collections` to `collections.abc` in 3.10 version. Currently nucleus is supported in python version upto 3.8.

**Comment by apilaskowski** [comment]
@kishwarshafin 

1. I am aware of this, however, it is still not building properly for me - I have run exactly this docker that I published earlier (pic as proof):
<img width="1080" alt="Screenshot 2022-07-02 at 01 09 19" src="https://user-images.githubusercontent.com/19377908/176976542-1e6397e6-b97a-4ca1-aeb3-1867c0628afc.png">

I think that abnormal part is the line with "Failed to build google-nucleus".

2. Yes, I found exactly that problem. I wanted to make it clear that I tried that approach and it didn't work to avoid questions about default build. Sorry, that it wasn't clear.

**Comment by pgrosu** [comment]
Hi @apilaskowski,

Just replace the following line in your Dockerfile:

``RUN python3.7 -m pip install google-nucleus``

with the following:

``RUN pip install --user google-nucleus``

and it will run successfully as shown below:

![image](https://user-images.githubusercontent.com/6555937/176982469-8b64ab57-16fb-400d-991c-1ae8b8793cc1.png)

Hope it helps,
~p

**Comment by apilaskowski** [comment]
Thanks @pgrosu!
It worked.

Do you know why it worked that way?

**Comment by pgrosu** [comment]
Hi Artur (@apilaskowski),

When you install packages via `-m` it generally goes through these steps (a complete explanation is available at https://realpython.com/python-wheels/):

1) Downloads a tar.gz of your package.
2) Builds a .whl (wheel) file through a call to setup.py.
3) Installs actual package after having built the wheel.

The issue is that Nucleus is specifically coded to not build wheels on the following lines:

https://github.com/google/nucleus/blob/v0.6.0/nucleus/pip_package/setup.py#L126-L128

```Python
  elif cmd == 'bdist_wheel':
    print('This package does not support wheel creation.')
    sys.exit(1)
```

So if you try the following commands it will never work:

```Bash
# curl https://files.pythonhosted.org/packages/bc/26/46196ddae6a25a7f2ca24ad37a42ac127aca46964a44bee74be2ed7018a1/google_nucleus-0.6.0.tar.gz --output google_nucleus-0.6.0.tar.gz
# tar xzvf google_nucleus-0.6.0.tar.gz
# cd google_nucleus-0.6.0
# python3.7 setup.py bdist_wheel
This package does not support wheel creation.
#
```

Hope it helps,
~p
