### ISSUE TITLE
PythonNext() argument read is not valid 

### ISSUE THREAD

**Issue by sivianil** [google/nucleus#44]
<img width="1310" alt="Screenshot 2023-07-03 at 22 15 18" src="https://github.com/google/nucleus/assets/75676816/7c6d3376-270e-43c0-ab24-7d66c896bba4">
Hello,
I'm working on fine-tuning the DeepVariant model on Arabidopsis thaliana. I developed the fine-tuned model trained on A.Thaliana data. While running this customised model on unseen data using singularity, I ran into an error 

### PythonNext() argument read is not valid: Dynamic cast failed. 

I have the tf and google-nucleus packages installed with versions,

1. tensorFlow 2.12.0
2. google-nucleus 0.6.0

**Comment by kishwarshafin** [comment]
Hello,

This looks like an error stemming from the bam file that you have. Seems like the way DeepVariant is seeing the bam file as truncated? Can you quickly sanity check the bam file to see if the file is OK? You can do that by running: http://www.htslib.org/doc/samtools-quickcheck.html

**Comment by sivianil** [comment]
There is nothing wrong with the bam file. I resolved the issue 2days ago by removing the packages in the local environment. It worked. Thanks for the reply :)
