### ISSUE TITLE
bigWig parser would be greatly appreciated

### ISSUE THREAD

**Issue by daquang** [google/nucleus#5]
Especially if it's faster than pyBigWig

**Comment by depristo** [comment]
We are interested in writing a bigwig parser. Do you have an example (ideally representative) bigwig file that is slow to parse with pyBigWig? Ideally you could point us to a commonly used bigwig file as well, via a URL, so we can review the licensing terms of any data we bring into the project?

**Comment by daquang** [comment]
Hi Mark,

pyBigWig has a test file (test.bw) on its github: https://github.com/deeptools/pyBigWig/tree/master/pyBigWigTest.

Typically, these parsers get slower with dense data (i.e. bigWig signal tracks that have non-zero values for most of the genome). .bigWig files from UW ENCODE (http://hgdownload.soe.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf/) are probably prime examples of dense bigWig files that I've encountered. You can find other ENCODE related bigWigs here: http://hgdownload.cse.ucsc.edu/gbdb/hg19/bbi/. Although, I imagine denser bigWig files are out there, and those files provide quite the challenge for parsing speed.

-Daniel

**Comment by pichuan** [comment]
Hi @daquang 
thanks for the feature request. We'll take it into account in the future. I've marked it with the "enhancement" label so it's easier for us to find later.
