### ISSUE TITLE
Any help with parsing .geno , .ind and .snp files?

### ISSUE THREAD

**Issue by vinayprabhu** [google/nucleus#7]
Hi Nucleus team,
The genotype- datasets shared on David Reich's repository here: https://reich.hms.harvard.edu/datasets
have (.geno, .ind, .snp) files and are parsable using only his lab's Eigensoft package: 
https://github.com/argriffing/eigensoft

Do you have any plans to support parsing these file formats?

Any help/advice in this regard would be much appreciated.
Thanks!

**Comment by cmclean** [comment]
Thanks for your interest in Nucleus! At the moment we have no concrete plans to support these formats. That said, we are currently working on the C++ APIs and documentation so that text-line-based formats will be easy to add.
