### ISSUE TITLE
pip installation check

### ISSUE THREAD

**Issue by cschin** [google/nucleus#8]
I just tried this

```
pip install --user google-nucleus
```

I got 
```
collecting google-nucleus
  Could not find a version that satisfies the requirement google-nucleus (from versions: )
No matching distribution found for google-nucleus
```

Just like to check if the package is properly set-up in PyPi.

**Comment by ThomasColthurst** [comment]
Interesting!  What sort of machine are you running this on?  If you could include the output of 
$ uname -a 
in your response, that would be most helpful.

Also, I assume you can pip-install other packages just fine?  (For example,
$ pip install --user six
works?)

**Comment by TommyBahamy** [comment]
I ran into the same issue. I'm working through a jupyterhub terminal and it returned "Linux" and "#211-Ubuntu" for my machine

**Comment by TommyBahamy** [comment]
My pip install --user works fine for base tensorflow and other packages as well.

**Comment by ThomasColthurst** [comment]
Hi, Tommy.  What version of Ubuntu are you running?  (uname -a should say that after the #211 Ubuntu part).

Also, can you try
$ python -m pip install google-nucleus
?

https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/ recommends this when installing pip packages into Jupyter notebooks.

**Comment by cschin** [comment]
it works today, not sure what was going on. Closing this issue.
