### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by fpreimesberger** [google/nucleus#9]
With `pip install --user google-nucleus` it gives the error  

> Could not find a version that satisfies the requirement google-nucleus (from versions: )
No matching distribution found for google-nucleus  

Is there a fix for this?  Machine is 18.04 Ubuntu

**Comment by ThomasColthurst** [comment]
Interesting!  Are you able to pip install other packages?  Also, are you by chance running a Python 3 version of pip?  (pip --version will tell you.)

Right now, the installed version of Nucleus is Python 3 compatible, but the pip package is Python 2 only.  We hope to fix that soon.

**Comment by ThomasColthurst** [comment]
Closing for now.  Please re-open with version info if problem persists.

**Comment by ajlogo** [comment]
>> Right now, the installed version of Nucleus is Python 3 compatible, but the pip package is Python 2 only. We hope to fix that soon.

The following should be qualified for pip for python 2 only
>> Nucleus currently only works on modern Linux systems. To install it, just run 
pip install --user google-nucleus

I guess it doesn't work with modern Python :)
Others trying to install in a Anacoda 3.x environment using pip (which in this case is pip3 ) will be stuck
 
Do I try to compile from source?
How else to install?

**Comment by ajlogo** [comment]
I would like to be a beta tester of a pip3 package.

I looked at trying to compile Nucleus. 
To compile from source, need to compile CLIF from source.
CLIF Prerequisites (from the CLIF Github install page)
Make sure CMake version 3.5 or later is available.  
We use Google protobuf for inter-process communication between the CLIF frontend and backend.  Please install protobuf for both C++ and Python from source, as we will need some protobuf source code later on.
You must have virtualenv installed.
You must have Subversion installed, so we can fetch LLVM.
You must have pyparsing installed, so we can build protobuf. Use pip install 'pyparsing>=2.2.0' to fetch the correct version.

I'm reminded of the Elliot Smith song    I got a long way to go Getting further away.

**Comment by ajlogo** [comment]
I would like to be a beta tester of a python/pip 3 install of Nucleus.
The Nucleus pip install instructions should include the condition of python 2 only.
I found this page after doing a search, and others may just stop at the pip 3 error.

I was able to install a python 2.7 environment inside of Anaconda 3 (Anaconda 3 is an anaconda version and does not imply python 3 environments only).
Installing the nucleus with pip worked.
Got the notebook to work locally with CPU.
The GPU version runs but repeats/recreates the following about 200 times:
  Created TensorFlow device 
full message:
2019-02-06 17:29:30.017084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6999 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:0a:00.0, compute capability: 6.1)


This may just be related to the number of batches.
The result is that the GPU time is about the same as the CPU time.

**Comment by TimSmole** [comment]
@ThomasColthurst is there any new information on when we can expect Nucleus to be available via pip for Python3 as well? 

Thanks!

**Comment by ThomasColthurst** [comment]
A Python 3 pip for Nucleus is probably a few weeks away.

**Comment by TimSmole** [comment]
@ThomasColthurst Perfect! Thanks for quick response. Also one more question - will Nucleus be compatible with Tensorflow 2.0 in the near future?

**Comment by ajlogo** [comment]
Thomas, Thank you very much

**Comment by ThomasColthurst** [comment]
@TimSmole -- yes.  We have an upcoming Nucleus release that removes our dependencies on TensorFlow's Python code, and this will make it easy to use Nucleus with whatever version of Tensorflow you want.

(Nucleus's C++ code will still depend on a specific version of TensorFlow, and that specific version will get upgraded to TensorFlow 2.0 once 2.0 is out of alpha.  But that shouldn't effect most Nucleus users.)

**Comment by TimSmole** [comment]
Great news! Thanks again @ThomasColthurst! I'm looking forward to this release.

**Comment by ThomasColthurst** [comment]
The long awaited Python 3-compatible pip package for Nucleus is now available.
